name: build
on: [push]
jobs:
  check-application:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build and Run Tests
        run: # execute your tests generating test results
      - name: Publish Test Report
        uses: action-junit-report@v2
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
